-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.36-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping data for table webapione.kundenstamm: ~98 rows (approximately)
/*!40000 ALTER TABLE `kundenstamm` DISABLE KEYS */;
INSERT IGNORE INTO `kundenstamm` (`OID`, `KDNr`, `Suchname`, `Anrede`, `Titel`, `Name1`, `Name2`, `Name3`, `Strasse`, `Nation`, `PLZ`, `Ort`, `eMail`, `Kundenart`, `kdauftrgesperrt`, `OptimisticLockField`, `GCRecord`) VALUES
	(1, 672536, 'Kröber', '', '', 'Kröber', 'Kristin', '', 'Eiler Straße 3W', '', 51107, 'Köln', 'kristin.kroeber@gedeonrichter.de', '', 'False', 1, ''),
	(2, 2041, 'Schwenn', '', '', 'Schwenn', 'Dr. Oliver', '', 'Joppenholzstraße 9', '', 67473, 'Lindenberg', 'oliver.schwenn@gedeonrichter.de', '3', 'False', 1, ''),
	(3, 2035, 'Rosniatowski', '', '', 'Rosniatowski', 'Susanne', '', 'Oberfeldstr. 9', '', 94360, 'Mitterfels', 'susanne.rosniatowski@gedeonrichter.de', '3', 'False', 1, ''),
	(4, 2034, 'Roge', '', '', 'Roge', 'Mario', '', 'Hecke 11 B', '', 47918, 'Tönisvorst', 'mario.roge@gedeonrichter.de', '3', 'False', 1, ''),
	(5, 2033, 'Reinartz', '', '', 'Reinartz', 'Björn', '', 'Im großen Garten 19', '', 57520, 'Langenbach bei Kirburg', 'bjoern.reinartz@gedeonrichter.de', '3', 'False', 1, ''),
	(6, 2007, 'Gemar', '', '', 'Gemar', 'Ilona', '', 'Westerfelder Weg 5', '', 24644, 'Timmaspe', 'ilona.gemar@gedeonrichter.de', '3', 'False', 1, ''),
	(7, 2024, 'Kruppa', '', '', 'Kruppa', 'Regina', '', 'Brunnenstraße 10', '', 96149, 'Breitengüßbach', 'regina.kruppa@gedeonrichter.de', '3', 'False', 1, ''),
	(8, 1001, 'Schorn', '', '', 'Schorn', 'Schorn', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'dagmar.schorn@gedeonrichter.de', '1', 'False', 1, ''),
	(9, 10119, 'Nachname', '', '', 'Nachname', 'Vorname', '', 'Musterstrasse 1', '', 75156, 'Musterort', 'test@test.de', '', 'False', 1, ''),
	(10, 1002, 'Seitz', '', '', 'Seitz', 'Marion', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'oliver.seitz@gedeonrichter.de', '1', 'False', 1, ''),
	(11, 1004, 'Klothen', '', '', 'Klothen', 'Carolin', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'carolin.klothen@gedeonrichter.de', '1', 'False', 1, ''),
	(12, 1005, 'Seitz', '', '', 'Seitz', 'Oliver', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'marion.seitz@gedeonrichter.de', '1', 'False', 1, ''),
	(13, 1006, 'Meyer', '', '', 'Meyer', 'Stefanie', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'stefanie.meyer@gedeonrichter.de', '1', 'False', 1, ''),
	(14, 1007, 'Natschke', '', '', 'Natschke', 'Gabriele', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'Gabriele.Natschke@gedeonrichter.de', '1', 'False', 1, ''),
	(15, 1008, 'Kröber', '', '', 'Kröber', 'Kristin ', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'kristin.kroeber@gedeonrichter.de', '1', 'False', 1, ''),
	(16, 1009, 'Müller', '', '', 'Müller', 'Astrid', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'astrid.mueller@gedeonrichter.de', '1', 'False', 0, ''),
	(17, 1010, 'Denker', '', '', 'Denker', 'Monika', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'monika.denker@gedeonrichter.de', '1', 'False', 1, ''),
	(18, 1011, 'Palm', '', '', 'Palm', 'Sabine', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'sabine.palm@gedeonrichter.de', '', 'False', 0, ''),
	(19, 1012, 'Lutterbach', '', '', 'Lutterbach', 'Ninette', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'nina.lutterbach@gedeonrichter.de', '1', 'False', 1, ''),
	(20, 1013, 'Nievejan', '', '', 'Nievejan', 'Sebastian', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'sebastian.nievejan@gedeonrichter.de', '1', 'False', 1, ''),
	(21, 1014, 'Krajewski', '', '', 'Krajewski', 'Vera', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'vera.krajewski@gedeonrichter.de', '1', 'False', 1, ''),
	(22, 1015, 'Fröse', '', '', 'Fröse', 'Daniela', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'daniela.froese@gedeonrichter.de', '1', 'False', 1, ''),
	(23, 1016, 'Hörburger ', '', '', 'Hörburger ', 'Andrea', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'andrea.hoerburger@gedeonrichter.de', '1', 'False', 1, ''),
	(24, 1017, 'Hellebrand ', '', '', 'Hellebrand ', 'Andreas', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'andreas.hellebrand@gedeonrichter.de', '1', 'False', 1, ''),
	(25, 1018, 'Scheffer', '', '', 'Scheffer', 'Nicole', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'nicole.scheffer@gedeonrichter.de', '1', 'False', 1, ''),
	(26, 1019, 'Mäßen', '', '', 'Mäßen', 'Jutta', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'jutta.maeßen@gedeonrichter.de', '1', 'False', 1, ''),
	(27, 1020, 'Rauch ', '', '', 'Rauch ', 'Paul', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'paul.rauch@gedeonrichter.de', '1', 'False', 1, ''),
	(28, 1021, 'Häger', '', '', 'Häger', 'Michaela', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'michaela.haeger@gedeonrichter.de', '1', 'False', 0, ''),
	(29, 1022, 'Augustynak', '', '', 'Augustynak', 'Maike ', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'Maike.Augustynak@gedeonrichter.de', '1', 'False', 1, ''),
	(30, 1023, 'Schreiner', '', '', 'Schreiner', 'Gabriele', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'gabi.schreiner@gedeonrichter.de', '1', 'False', 1, ''),
	(31, 1024, 'Feck', '', '', 'Feck', 'Bernadette', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'bernadette.feck@gedeonrichter.de', '1', 'False', 1, ''),
	(32, 1026, 'Lueckeroth', '', '', 'Lueckeroth', 'Hildegard', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'Hildegard.Lueckeroth@gedeonrichter.de', '1', 'False', 1, ''),
	(33, 1027, 'Dummy/Kongress', '', '', 'Dummy/Kongress', 'Dummy/Kongress', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'service@gedeon richter.de ', '1', 'False', 1, ''),
	(34, 1028, 'Dummy/Abruf Zentrale', '', '', 'Dummy/Abruf Zentrale', 'Dummy/Abruf Zentrale', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'service@gedeon richter.de ', '1', 'False', 1, ''),
	(35, 1029, 'Dummy/externe Kunden', '', '', 'Dummy/externe Kunden', 'Dummy/externe Kunden', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'service@gedeon richter.de ', '1', 'False', 1, ''),
	(36, 1030, 'Hartmann', '', '', 'Hartmann', 'Björn', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'Bjoern.Hartmann@gedeonrichter.de', '1', 'False', 1, ''),
	(37, 1031, 'Samimi', '', '', 'Samimi', 'Melanie', '', 'Eiler Str. 3 W', '', 51107, 'Köln ', 'Melanie.Samimi-Ghairaiy@gedeonrichter.de', '1', 'False', 1, ''),
	(38, 1032, 'Godin', '', '', 'Godin', 'Agnes', '', 'Mergenthalerallee 15-21', '', 65760, 'Eschborn ', 'Agnes.Godin@gedeonrichter.de', '1', 'False', 1, ''),
	(39, 2000, 'Bannier ', '', '', 'Bannier ', 'Hans', '', 'Klosterstr.12', '', 4931, 'Mühlberg/Elbe', 'hans.bannier@gedeonrichter.de', '3', 'False', 1, ''),
	(40, 2001, 'Bettinger', '', '', 'Bettinger', 'Andrea', '', 'Kaiser-Friedrich-Ring 6', '', 66740, 'Saarlouis', 'andrea.bettinger@gedeonrichter.de', '3', 'False', 1, ''),
	(41, 2002, 'Braun-Bialdiga', '', '', 'Braun-Bialdiga', 'Gabriele', '', 'Silvanerstraße 19', '', 55129, 'Mainz ', 'gabriele.braun-bialdiga@gedeonrichter.de', '3', 'False', 1, ''),
	(42, 2003, 'Ehrt', '', '', 'Ehrt', 'Kerstin', '', 'Neue Straße 139', '', 99439, 'Großobringen', 'kerstin.ehrt@gedeonrichter.de', '3', 'False', 1, ''),
	(43, 2004, 'Felker', '', '', 'Felker', 'Mikaela', '', 'Hirtenweg 3 ', '', 59439, 'Holzwickede', 'mikaela.felker@gedeonrichter.de', '3', 'False', 1, ''),
	(44, 2005, 'Friedemann', '', '', 'Friedemann', 'Ann-Kathrin', '', 'Talstraße 10', '', 9434, 'Zschopau/ OT Krumhermersdorf ', 'ann-kathrin.friedemann@gedeonrichter.de', '3', 'False', 1, ''),
	(45, 2008, 'Gerbert', '', '', 'Gerbert', 'Corinna', '', 'Grevener Damm 59', '', 48346, 'Ostbeveren ', 'corinna.gerbert@gedeonrichter.de', '3', 'False', 1, ''),
	(46, 2009, 'Lausch', '', '', 'Lausch', 'Sibylle', '', 'Schwander Straße 23 a', '', 91126, 'Rednitzhembach', 'sibylle.lausch@gedeonrichter.de', '3', 'False', 1, ''),
	(47, 2010, 'Gramann', '', '', 'Gramann', 'Michael', '', 'Kreuze 21', '', 63505, 'Langenselbold', 'michael.gramann@gedeonrichter.de', '3', 'False', 1, ''),
	(48, 2012, 'Heidbreder de Boer', '', '', 'Heidbreder de Boer', 'Stefan', '', 'Dachsweg 13', '', 44267, 'Dortmund', 'stefan.heidbreder-deboer@gedeonrichter.de', '3', 'False', 1, ''),
	(49, 2013, 'Heyden', '', '', 'Heyden', 'Susanne', '', 'Freiligrathstr. 33 a', '', 14656, 'Brieselang', 'susanne.heyden@gedeonrichter.de', '3', 'False', 1, ''),
	(50, 2014, 'Hübner ', '', '', 'Hübner', 'Anne', '', 'Talstraße 15', '', 78351, 'Bodman-Ludwigshafen  ', 'anne.hinsen@gedeonrichter.de', '3', 'False', 1, ''),
	(51, 2017, 'Jung', '', '', 'Jung', 'Margot', '', 'Gäustraße 40', '', 67435, 'Neustadt', 'margot.jung@gedeonrichter.de', '3', 'False', 1, ''),
	(52, 2018, 'Kaschel', '', '', 'Kaschel', 'Monika', '', 'Hans-Böckler-Straße 274', '', 46242, 'Bottrop', 'monika.kaschel@gedeonrichter.de', '3', 'False', 1, ''),
	(53, 2019, 'Starke', '', '', 'Starke', 'Sylvia', '', 'Zillerstraße 4', '', 1445, 'Radebeul', 'Sylvia.Starke@gedeonrichter.de', '3', 'False', 1, ''),
	(54, 2020, 'Klewer', '', '', 'Klewer', 'Diana', '', 'Himbeerweg 6', '', 70619, 'Stuttgart', 'diana.klewer@gedeonrichter.de', '3', 'False', 1, ''),
	(55, 2021, 'Klobukowski', '', '', 'Klobukowski', 'Margarete', '', 'Karl-Marx-Straße 139d', '', 12529, 'Schönefeld', 'margarete.klobukowski@gedeonrichter.de', '3', 'False', 1, ''),
	(56, 2022, 'Kossack', '', '', 'Kossack', 'Bianka', '', 'Eilenburger Straße 24', '', 4317, 'Leipzig', 'bianka.kossack@gedeonrichter.de', '3', 'False', 1, ''),
	(57, 2023, 'Krüger', '', '', 'Krüger', 'Terje', '', 'Drosselweg 39', '', 31840, 'Hessisch-Oldendorf', 'terje.krueger@gedeonrichter.de', '3', 'False', 1, ''),
	(58, 2025, 'Lay', '', '', 'Lay', 'Jasmin', '', 'Kirchgasse 5', '', 87746, 'Erkeim OT Daxberg', 'jasmin.lay@gedeonrichter.de', '3', 'False', 1, ''),
	(59, 2026, 'Leditzke', '', '', 'Leditzke', 'Paul-Erhard', '', 'Glockenheide 1', '', 32289, 'Rödinghausen', 'paul-erhard.leditzke@gedeonrichter.de', '3', 'False', 1, ''),
	(60, 2028, 'Liesch', '', '', 'Liesch', 'Sabine', '', 'Wiedestraße 4a', '', 22880, ' Wedel', 'sabine.liesch@gedeonrichter.de', '3', 'False', 1, ''),
	(61, 2029, 'Lohmann', '', '', 'Lohmann', 'Dagmar', '', 'Günther-Tietjen-Ring 49', '', 26789, 'Leer', 'dagmar.lohmann@gedeonrichter.de', '3', 'False', 1, ''),
	(62, 2030, 'Eberhardt', '', '', 'Eberhardt', 'Ramona', '', 'Keltenstraße 4', '', 85254, 'Einsbach', ' Ramona.Eberhardt@gedeonrichter.de', '3', 'False', 1, ''),
	(63, 2032, 'Munz', '', '', 'Munz', 'Friederike', '', 'Hans-Sachs-Weg 12', '', 71332, 'Waiblingen', 'friederike.munz@gedeonrichter.de', '3', 'False', 1, ''),
	(64, 2036, 'Rössler', '', '', 'Rössler', 'Regina', '', 'Zur Rur 19a', '', 52428, 'Jülich', 'regina.roessler@gedeonrichter.de', '3', 'True', 1, ''),
	(65, 2038, 'Scheve', '', '', 'Scheve', 'Sabine', '', 'Iltisweg 18', '', 26131, 'Oldenburg', 'sabine.scheve@gedeonrichter.de', '3', 'False', 1, ''),
	(66, 2039, 'Schur', '', '', 'Schur', 'Susanne', '', 'Schubertstraße 31', '', 86368, 'Gersthofen', 'susanne.schur@gedeonrichter.de', '3', 'False', 1, ''),
	(67, 2040, 'Schuster', '', '', 'Schuster', 'Katrin', '', 'Wiesenweg 9', '', 8427, 'Fraureuth', 'katrin.schuster@gedeonrichter.de', '3', 'False', 1, ''),
	(68, 2042, 'Szczepanski', '', '', 'Szczepanski', 'Elke', '', 'Hecke 11 B', '', 47918, 'Tönisvorst', 'elke.szczepanski@gedeonrichter.de', '3', 'False', 1, ''),
	(69, 2043, 'Thomann', '', '', 'Thomann', 'Ildiko', '', 'Brunnenstraße 18', '', 76307, 'Karlsbad', 'ildiko.thomann@gedeonrichter.de', '3', 'False', 1, ''),
	(70, 2044, 'Urruchi Corzo', '', '', 'Urruchi Corzo', 'Carlos', '', 'Kastanienweg 12a', '', 85757, 'Karlsfeld', 'carlos.urruchi@gedeonrichter.de', '3', 'False', 1, ''),
	(71, 2052, 'Wählte', '', '', 'Wählte', 'Astrid', '', 'Teltow', '', 14513, 'Beethofenstr. 20 a', 'astrid.waehlte@gedeonrichter.de', '3', 'False', 1, ''),
	(72, 2045, 'Weber', '', '', 'Weber', 'Barbara', '', 'Lerchenweg 12', '', 91126, 'Rednitzhembach', 'barbara.weber@gedeonrichter.de', '3', 'False', 1, ''),
	(73, 2046, 'Wehrland', '', '', 'Wehrland', 'Berthold', '', 'Am Eichenhof 4', '', 45739, 'Oer-Erkenschwick', 'berthold.wehrland@gedeonrichter.de', '3', 'False', 1, ''),
	(74, 2048, 'Willems', '', '', 'Willems', 'Michael', '', 'Im Kamp 54', '', 49152, 'Bad Essen', 'michael.willems@gedeonrichter.de', '3', 'False', 1, ''),
	(75, 2049, 'Winkler', '', '', 'Winkler', 'Karina', '', 'Hufelandstr. 28', '', 18059, ' Rostock', 'karina.winkler@gedeonrichter.de', '3', 'False', 1, ''),
	(76, 2050, 'Wizani', '', '', 'Wizani', 'Peter', '', 'Im Landgraben 5', '', 71717, 'Beilstein', 'peter.wizani@gedeonrichter.de', '3', 'False', 1, ''),
	(77, 2051, 'Wölm', '', '', 'Wölm', 'Angelika', '', 'Feldstraße 17a', '', 14558, 'Nuthetal', 'angelika.woelm@gedeonrichter.de', '3', 'False', 1, ''),
	(78, 3000, 'Abo-Dalo', '', '', 'Abo-Dalo', 'Benjamin', '', 'Alter Schulweg 1', '', 25373, ' Ellerhoop', 'benjamin.abo-dalo@gedeonrichter.de', '2', 'False', 1, ''),
	(79, 3001, 'Braun', '', '', 'Braun', 'Christina', '', 'Rheinstraße 86', '', 72768, 'Reutlingen', 'christina.braun@gedeonrichter.de', '2', 'False', 1, ''),
	(80, 3002, 'El Yacoubi', '', '', 'El Yacoubi', 'Franziska', '', 'Hans-Sachs-Straße 68', '', 65428, 'Rüsselsheim', 'franziska.elyacoubi@gedeonrichter.de', '2', 'False', 1, ''),
	(81, 3003, 'Halupczok', '', '', 'Halupczok', 'Hubert', '', 'Brunnacker 6', '', 94154, 'Neukirchen vorm Wald', 'hubert.halupczok@gedeonrichter.de', '2', 'False', 1, ''),
	(82, 3004, 'Kessler ', '', '', 'Kessler ', 'Christop', '', 'Nadorster Straße 162 B', '', 26123, 'Oldenburg', 'christoph.kessler@gedeonrichter.de', '2', 'False', 1, ''),
	(83, 4000, 'Pesselt', '', '', 'Pesselt', 'Ivia', '', 'Gehlsheimer Str. 4', '', 18147, 'Rostock', 'ivia.pesselt@gedeonrichter.de', '4', 'False', 1, ''),
	(84, 4001, 'Schmidt', '', '', 'Schmidt', 'Oskar', '', 'Eichenweg 3', '', 72076, 'Tübingen', 'oskar.schmidt@gedeonrichter.de', '4', 'False', 1, ''),
	(85, 4002, 'Feldhaus', '', '', 'Feldhaus', 'Gunnar', '', 'Schlesierweg 10', '', 58239, 'Schwerte', 'gunnar.feldhaus@gedeonrichter.de', '4', 'False', 1, ''),
	(86, 4003, 'Sparschuh', '', '', 'Sparschuh', 'Thomas', '', 'Im Dömpel 4', '', 56727, 'Sankt Johann', 'thomas.sparschuh@gedeonrichter.de', '4', 'False', 1, ''),
	(87, 4004, 'Erny', '', '', 'Erny', 'Roland', '', 'Stadtpark 65', '', 91413, 'Neustadt a. d. Aisch', 'roland.erny@gedeonrichter.de', '4', 'False', 1, ''),
	(88, 1000, 'Horvath', '', '', 'Horvath', 'Tibor', '', 'Eiler Str. 3 W', '', 51107, 'Köln', 'tibor.horvath@gedeonrichter.de', '1', 'False', 1, ''),
	(89, 1003, 'Wilkinson, Sabrina', '', '', 'Sabrina', 'Wilkinson', '', 'Severinstrasse 15', '', 47877, 'Willich', 'Sabrina.Wilkinson@gedeonrichter.de', '', 'False', 1, ''),
	(90, 1025, 'Hübner, Anne', '', '', 'Anne', 'Hinsen', '', 'Talstraße 15', '', 78351, 'Bodman-Ludwigshafen', 'Anne.Huebner@gedeonrichter.de', '', 'False', 1, ''),
	(91, 2054, 'Jarosch, Bettina', '', '', '', 'Jarosch', 'Bettina', 'Steinberg 1', '', 53819, 'Neunkirchen-Seelscheid', 'Bettina.Jarosch@gedeonrichter.de', '3', 'False', 1, ''),
	(92, 2053, 'Oltzow, Rainer', '', '', '', 'Oltzow', 'Rainer', 'Weserstraße 12', '', 34454, 'Bad Arolsen', 'Rainer.Oltzow@gedeonrichter.de', '3', 'False', 1, ''),
	(93, 2055, 'FUSS', '', '', 'Fuss', 'Tanja', '', 'Florastraße 19', '', 36093, 'Künzell', 'Tanja.Fuss@gedeonrichter.de', '5', 'False', 1, ''),
	(94, 1034, 'KIRSCH', '', '', 'Kirsch', 'Mainolf', '', 'Eiler Str. 3', '', 51107, 'Köln', 'Meinolf.Kirsch@gedeonrichter.de', '1', 'False', 1, ''),
	(95, 2056, 'Scharfenberg', '', '', 'Scharfenberg', 'Cornelia', '', 'Forsthaus 33', '', 40883, 'Ratingen', 'cornelia.scharfenberg@gedeonrichter.de', '', 'False', 1, ''),
	(96, 1035, 'WOLTER', '', '', 'Wolter', 'Monika', '', 'Eiler Str. 3 W', '', 51107, 'Köln', '', '', 'False', 1, ''),
	(97, 1036, 'SCHNEIDERS', '', '', 'Schneiders', 'Angelika', '', 'Eiler Str. 3 W', '', 51107, 'Köln', '', '', 'False', 1, ''),
	(98, 1037, 'BIHRER', '', '', 'Bihrer', 'Nicole', '', 'Eiler Str. 3 W', '', 51107, 'Köln', '', '', 'False', 1, '');
/*!40000 ALTER TABLE `kundenstamm` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
